### ISSUE TITLE
Can't install to python 3.6

### ISSUE THREAD

**Issue by bondeanikets** [pgaref/HTTP_Request_Randomizer#41]
When I try with pip, error is:
Could not find a version that satisfies the requirement HTTP_Request_Randomizer-master (from versions: )
No matching distribution found for HTTP_Request_Randomizer-master

When I try as 'python setup.py install', error is:
zip_safe flag not set; analyzing archive contents...

Installed c:\users\anike\http_request_randomizer-master\.eggs\pytest_runner-3.0-py3.6.egg
Searching for setuptools-scm
Reading https://pypi.python.org/simple/setuptools-scm/
Downloading https://pypi.python.org/packages/40/fa/d4fff7846c36909846c2148990cdb01e77e62d59ee4d19ca872a60844475/setuptools_scm-1.15.7-py3.6.egg#md5=77134e6f8cfebd07c7e4fd2b7c775b7a
Best match: setuptools-scm 1.15.7
Processing setuptools_scm-1.15.7-py3.6.egg
Moving setuptools_scm-1.15.7-py3.6.egg to c:\users\anike\http_request_randomizer-master\.eggs

Installed c:\users\anike\http_request_randomizer-master\.eggs\setuptools_scm-1.15.7-py3.6.egg
Traceback (most recent call last):
  File "setup.py", line 98, in <module>
    'Topic :: Software Development :: Libraries :: Python Modules',
  File "C:\Users\anike\Anaconda3\lib\distutils\core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "C:\Users\anike\Anaconda3\lib\site-packages\setuptools\dist.py", line 338, in __init__
    _Distribution.__init__(self, attrs)
  File "C:\Users\anike\Anaconda3\lib\distutils\dist.py", line 281, in __init__
    self.finalize_options()
  File "C:\Users\anike\Anaconda3\lib\site-packages\setuptools\dist.py", line 471, in finalize_options
    ep.load()(self, ep.name, value)
  File "c:\users\anike\http_request_randomizer-master\.eggs\setuptools_scm-1.15.7-py3.6.egg\setuptools_scm\integration.py", line 22, in version_keyword
  File "c:\users\anike\http_request_randomizer-master\.eggs\setuptools_scm-1.15.7-py3.6.egg\setuptools_scm\__init__.py", line 119, in get_version
  File "c:\users\anike\http_request_randomizer-master\.eggs\setuptools_scm-1.15.7-py3.6.egg\setuptools_scm\__init__.py", line 97, in _do_parse
LookupError: setuptools-scm was unable to detect version for 'C:\\Users\\anike\\HTTP_Request_Randomizer-master'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj

Help needed,
Thanks!

**Comment by pgaref** [comment]
Hello @bondeanikets, 

Thanks for reporting! I didn't see this coming as travis build for 3.6 seems fine.
Did you try the latest version from master? I guess you can still invoke the runner scripts from the project, even if it is not installed, right?

I will take a look at this as soon as possible :)

**Comment by bondeanikets** [comment]
Invoking the runner scripts from the project works, thanks!
